### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/place-16s#2]
Let's use python:3.8-buster at the base image and install dependencies on top

eg
```
docker run -it --rm python:3.8-buster
```

Refer to https://github.com/nhoffman/dada2-nf/tree/master/docker as a template for creating the docker image

**Comment by crosenth** [comment]
https://github.com/nhoffman/place-16s/commit/f95784ab85c569f54579a57c03648ce76be21843

**Comment by crosenth** [comment]
https://github.com/nhoffman/place-16s/blob/master/dockerfiles/Dockerfile
