### ISSUE TITLE
NF pipeline outline

### ISSUE THREAD

**Issue by crosenth** [nhoffman/place-16s#3]
Based off 16s-capture:

process cmalign
process merge
process get_consensus
process epa
process gappa
process get_classifications
process read_depth
process read_stats

@nhoffman

**Comment by nhoffman** [comment]
@crosenth - what happens in get_consensus, read_depth, and read_stats?

**Comment by crosenth** [comment]
process cmalign
process merge
process epa
process gappa
process get_classifications

**Comment by crosenth** [comment]
process taxon_file
process cmalign
process merge
process get_model_descriptor
process epa
process gappa
process get_classifications

**Comment by crosenth** [comment]
process taxon_file
process cmalign
process merge
process get_model_descriptor
process epa
process gappa
process get_classifications
process sv_table

**Comment by crosenth** [comment]
https://github.com/nhoffman/place-16s/blob/master/main.nf
